### ISSUE TITLE
ApplicationNotResponding on certain devices with flutter_inappwebview

### ISSUE THREAD

**Issue by vishnukvmd** [ente-io/frame#12]
Root issue: https://github.com/pichillilorenzo/flutter_inappwebview/issues/855

Stacktrace:
```
io.sentry.android.core.ApplicationNotResponding: Application Not Responding for at least 4000 ms.
    at J.N.M1Y_XVCN(chromium-SystemWebViewGoogle.aab-stable-443021003)
    at org.chromium.content.browser.BrowserStartupControllerImpl.a(chromium-SystemWebViewGoogle.aab-stable-443021003:2)
    at org.chromium.content.browser.BrowserStartupControllerImpl.g(chromium-SystemWebViewGoogle.aab-stable-443021003:8)
    at L7.run(chromium-SystemWebViewGoogle.aab-stable-443021003:23)
    at org.chromium.base.ThreadUtils.f(chromium-SystemWebViewGoogle.aab-stable-443021003:2)
    at mu0.i(chromium-SystemWebViewGoogle.aab-stable-443021003:31)
    at mu0.b(chromium-SystemWebViewGoogle.aab-stable-443021003:17)
    at com.android.webview.chromium.WebViewChromiumFactoryProvider.getWebStorage(chromium-SystemWebViewGoogle.aab-stable-443021003:4)
    at android.webkit.WebStorage.getInstance(WebStorage.java:194)
    at com.pichillilorenzo.flutter_inappwebview.MyWebStorage.<init>
    at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine
    at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine
    at io.flutter.embedding.engine.c.a
    at io.flutter.plugins.GeneratedPluginRegistrant.registerWith
    at java.lang.reflect.Method.invoke(Method.java)
    at io.flutter.embedding.engine.h.h.a.a
    at io.flutter.embedding.android.j.i
    at io.flutter.embedding.android.i.i
    at io.flutter.embedding.android.e.k
    at io.flutter.embedding.android.i.A0
    at androidx.fragment.app.Fragment.f1
    at androidx.fragment.app.u.c
    at androidx.fragment.app.u.m
    at androidx.fragment.app.n.d0
    at androidx.fragment.app.n.c1
    at androidx.fragment.app.n.a0
    at androidx.fragment.app.n.S
    at androidx.fragment.app.n.y
    at androidx.fragment.app.i.c
    at androidx.fragment.app.e.onStart
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1245)
    at android.app.Activity.performStart(Activity.java:6364)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2540)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2665)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1499)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:207)
    at android.app.ActivityThread.main(ActivityThread.java:5765)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by ua741** [comment]
Shall we close this issue? There's no activity for close to one year...
